[book]
title = "Today I Learned"
description = "Snippets, Thoughts and Notes"
authors = ["Jan-Erik"]
language = "en"
src = "src"

[rust]
edition = "2018"

[build]
build-dir = "_book"
create-missing = false

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/badboy/til"
edit-url-template = "https://github.com/badboy/til/edit/main/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
